Redesign nav
Interviewboom/frontend pull request #31
Opened 2023-05-21 18:39 UTC by Pavlo-Tymoshchuk

Redesign nav.
Little bit updated mobile version (design) with sub menu and added button for open sub menu.
Added component "ButtonLikeLink" in Link.
+ Waiting new logo in footer-redesign

2023-05-22 18:31 UTC, karinabarinova requested changes

2023-05-22 18:31 UTC, karinabarinova commented on src/components/modules/Header/Header.tsx
> +                    <Logo redirectToHome />
Please update the Logo according to the design

2023-05-22 18:31 UTC, karinabarinova commented on src/components/modules/Header/helpers/const.ts
> +const LINK_OUR_TESTS = "#about-us";
Shouldn't it point to the test page?

2023-05-22 18:31 UTC, karinabarinova commented on src/components/modules/Header/components/Navigation.module.scss
> +
```suggestion
    white-space: nowrap;
```

2023-05-22 18:31 UTC, karinabarinova commented on src/components/modules/Header/components/Auth.module.scss
> +}
```suggestion
    white-space: nowrap;
}
```

2023-05-22 18:31 UTC, karinabarinova commented on src/components/modules/Header/Header.tsx
> +                <Logo redirectToHome />
The Logo needs to be updated

2023-05-22 18:31 UTC, karinabarinova commented on src/components/elements/Link/ButtonLikeLink.types.ts
> +    color?: "white";
Is this added for a possible dark theme implementation? 
I can see that we don't have the styles for white color option.

2023-05-29 19:09 UTC, kas1qqqq requested changes

2023-05-29 19:09 UTC, kas1qqqq commented on src/components/modules/Header/components/Auth.tsx
> +import { AUTH_ITEMS } from "../helpers/const";
reorder imports fitted rules

2023-05-29 19:09 UTC, kas1qqqq commented on src/components/modules/Header/components/Navigation.tsx
> +import { NAVIGATION_ITEMS } from "../helpers/const";
reorder imports fitted rules

2023-05-29 19:09 UTC, kas1qqqq commented on src/components/modules/Header/components/NavigationSubBlock.tsx
> +import { NavigationItem, NavigationProps } from "../Header.types";
the same trouble)

2023-06-03 15:27 UTC, Pavlo-Tymoshchuk commented on src/components/modules/Header/Header.tsx
> +                <Logo redirectToHome />
Updated.

2023-06-12 20:23 UTC, karinabarinova approved these changes

2023-06-21 08:54 UTC, Flowerinno approved these changes
lgtm

2023-06-21 12:11 UTC, kas1qqqq approved these changes

2023-06-21 12:13 UTC, merged