Feature/auth header layout
Interviewboom/frontend pull request #35
Opened 2023-05-29 18:40 UTC by kas1qqqq

2023-05-29 18:43 UTC, kas1qqqq commented
<img width="961" alt="SCR-20230529-soiu" src="https://github.com/Interviewboom/frontend/assets/29861553/4bbf62a8-c484-4d86-97a2-10cafa10233f">

2023-05-29 18:50 UTC, kas1qqqq commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Auth Layout for authentication-related pages](https://trello.com/c/akHHQUvz/94-add-auth-layout-for-authentication-related-pages)

2023-05-29 21:02 UTC, Flowerinno commented
we have a typo in subtitle 
` Once you're done you'll get access to your personalised roadmap `

2023-05-29 21:06 UTC, Flowerinno commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +            border-bottom: 0.1rem $primary-dark solid;
for borders, box-shadows we're sticking to px
```suggestion
            border-bottom: 0.1px $primary-dark solid;
```

2023-05-29 21:09 UTC, Flowerinno commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +            }
maybe i don't get it , but why use :not pseudo part here if it's not hovered just apply styles to .backBtnText

2023-05-29 21:14 UTC, Flowerinno commented on src/components/modules/AuthHeader/AuthHeader.tsx
> +import React, { FC, ReactNode } from "react";
you can remove unused React import

2023-05-29 21:18 UTC, Flowerinno commented on src/components/modules/AuthHeader/AuthHeader.tsx
> +            </div>
div with `role='button'` is kinda bad for semantics 
something like that would be better
```suggestion
            <button
                tabIndex={0}
                className={styles.backBtnContainer}
                onClick={handleBack}
                onKeyDown={handleKeyDown}
            >
                <Icon name="arrowLeft" width={10} height={10} className={styles.arrowLeftIcon} />
                <span className={styles.backBtnText}>back</span>
            </button>
```

2023-05-29 21:19 UTC, Flowerinno requested changes
fix

2023-05-30 05:23 UTC, kas1qqqq commented
> we have a typo in subtitle `Once you're done you'll get access to your personalised roadmap`
It isn’t my typo, I added only the header layout.

2023-05-30 05:33 UTC, kas1qqqq commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +            border-bottom: 0.1rem $primary-dark solid;
replaced

2023-05-30 05:37 UTC, kas1qqqq commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +            }
I tried to add smooth animation if the mouse left the block. But yes, it's unnecessary, so I’ll add it to the main class.

2023-05-30 05:39 UTC, kas1qqqq commented on src/components/modules/AuthHeader/AuthHeader.tsx
> +import React, { FC, ReactNode } from "react";
> 

I use it in this cause: `function handleKeyDown(e: React.KeyboardEvent<HTMLDivElement>)`

2023-05-30 05:50 UTC, kas1qqqq commented on src/components/modules/AuthHeader/AuthHeader.tsx
> +            </div>
In this case, div acts like a button, and I left a button tag to fit his in one style. And to avoid errors I follow these rules: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/f0d2ddb65f21278ad29be43fb167a1092287b4b1/docs/rules/no-static-element-interactions.md

2023-05-31 17:20 UTC, karinabarinova requested changes

2023-05-31 17:20 UTC, karinabarinova commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +            margin-top: 1px;
```suggestion
            margin-top: 0.1rem;
```

2023-05-31 17:20 UTC, karinabarinova commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +                margin-top: 4px;
```suggestion
                margin-top: 0.4rem;
```

2023-05-31 17:20 UTC, karinabarinova commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +                padding-bottom: 3px;
```suggestion
                padding-bottom: 0.3rem;
```

2023-05-31 17:40 UTC, karinabarinova approved these changes

2023-05-31 20:45 UTC, kas1qqqq commented on src/components/modules/AuthHeader/AuthHeader.module.scss
> +            display: none;
removed

2023-05-31 22:19 UTC, kas1qqqq commented
> fix

Fixed

2023-06-01 10:22 UTC, karinabarinova approved these changes

2023-06-01 15:03 UTC, Flowerinno approved these changes

2023-06-01 21:20 UTC, merged