Redesign popular tests section
Interviewboom/frontend pull request #41
Opened 2023-06-11 14:37 UTC by karinabarinova

https://trello.com/c/9CGxWgiL/80-redesign-popular-tests-section

2023-06-21 11:42 UTC, Flowerinno approved these changes
bomba

2023-06-22 09:53 UTC, kas1qqqq requested changes

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/elements/Text/Text.tsx
> +    semiBold?: true | false;
``` suggestion
    semiBold?: boolean;
```

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/elements/Button/Button.module.scss
> +    font-family: inherit;
will come globally in a future PR
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/elements/Button/Button.module.scss
>      font-style: normal;
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/elements/Error/Error.module.scss
>      font-style: normal;
I’m not sure about necessary it
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/modules/Footer/NavigationList.module.scss
>                  font-style: normal;
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/modules/Header/Auth.module.scss
>      font-style: normal;
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/modules/Header/Header.module.scss
>      z-index: 999;
if enough
```suggestion
    z-index: 1 or 2;
```

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/modules/Header/Navigation.module.scss
>      font-style: normal;
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/modules/TestsSection/TestsSectionDesktop.module.scss
>      font-weight: 600;
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/modules/TestsSection/TestsSectionMobile.module.scss
>      font-weight: 500;
```suggestion

2023-06-22 09:53 UTC, kas1qqqq commented on src/pages/all-tests.tsx
> -
```suggestion
why did you delete it?

2023-06-22 09:53 UTC, kas1qqqq commented on src/components/elements/Logo/Logo.module.scss
>          font-style: normal;
```suggestion

2023-06-24 17:59 UTC, karinabarinova commented on src/pages/all-tests.tsx
> -
We're able to get the tests data without authentication now.

2023-06-24 18:18 UTC, karinabarinova commented on src/components/elements/Text/Text.tsx
> +    semiBold?: true | false;
These changes can be applied with a separate MR, as it does not concern the changes of this task.

2023-06-24 18:19 UTC, karinabarinova commented on src/components/elements/Button/Button.module.scss
> +    font-family: inherit;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/elements/Button/Button.module.scss
>      font-style: normal;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/elements/Error/Error.module.scss
>      font-style: normal;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/modules/Footer/NavigationList.module.scss
>                  font-style: normal;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/modules/Header/Auth.module.scss
>      font-style: normal;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/modules/Header/Header.module.scss
>      z-index: 999;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/modules/Header/Navigation.module.scss
>      font-style: normal;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/modules/TestsSection/TestsSectionDesktop.module.scss
>      font-weight: 600;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/modules/TestsSection/TestsSectionMobile.module.scss
>      font-weight: 500;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 18:19 UTC, karinabarinova commented on src/components/elements/Logo/Logo.module.scss
>          font-style: normal;
[Same](https://github.com/Interviewboom/frontend/pull/41#discussion_r1240913302)

2023-06-24 20:24 UTC, kas1qqqq approved these changes

2023-06-25 13:35 UTC, merged