Error handler for auth pages
Interviewboom/frontend pull request #42
Opened 2023-06-18 18:43 UTC by kas1qqqq

2023-06-18 19:54 UTC, kas1qqqq commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wrong error handling for sign in/sign up pages](https://trello.com/c/f9Su31G3/117-wrong-error-handling-for-sign-in-sign-up-pages)

2023-06-21 18:01 UTC, kas1qqqq commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wrong error handling for sign in/sign up pages](https://trello.com/c/f9Su31G3/117-wrong-error-handling-for-sign-in-sign-up-pages)

2023-06-21 18:04 UTC, kas1qqqq commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wrong error handling for sign in/sign up pages](https://trello.com/c/f9Su31G3/117-wrong-error-handling-for-sign-in-sign-up-pages)

2023-06-21 20:31 UTC, karinabarinova requested changes

2023-06-21 20:31 UTC, karinabarinova commented on src/components/elements/Auth/Auth.tsx
> +    error?: ErrorProps | any;
Is there any specific reason why we have `any` here?

2023-06-21 20:31 UTC, karinabarinova commented on src/components/elements/Error/Error.tsx
> +    semiBold?: true | false;
```suggestion
    semiBold?: boolean;
```

2023-06-21 20:31 UTC, karinabarinova commented on src/components/elements/Title/Title.tsx
> +    semiBold?: true | false;
```suggestion
    semiBold?: boolean;
```

2023-06-21 20:31 UTC, karinabarinova commented on src/components/modules/ResetPasswordSection/ResetPasswordForm.tsx
> +            {textFields.map(({ type, placeholder, value, error: err, name }) => (
Why are we renaming the error field here?

2023-06-21 20:31 UTC, karinabarinova commented on src/components/modules/SignInSection/SignInForm.tsx
> +    const isFetchBaseQueryError = (err: unknown): err is FetchBaseQueryError => {
Let's move this function to a util file.

2023-06-21 20:31 UTC, karinabarinova commented on src/components/modules/SignUpSection/SignUpForm.tsx
> +    const isFetchBaseQueryError = (err: unknown): err is FetchBaseQueryError => {
Once the function has been moved to a util file, we can reuse it in this file as well

2023-06-21 20:35 UTC, kas1qqqq commented on src/components/modules/ResetPasswordSection/ResetPasswordForm.tsx
> +            {textFields.map(({ type, placeholder, value, error: err, name }) => (
Case in sign in sign up components already exist error object from rtk query

2023-06-21 20:39 UTC, kas1qqqq commented on src/components/elements/Auth/Auth.tsx
> +    error?: ErrorProps | any;
Ts can’t define what is will be come from server, maybe you can help fix it

2023-06-21 20:40 UTC, kas1qqqq commented on src/components/modules/SignInSection/SignInForm.tsx
> +    const isFetchBaseQueryError = (err: unknown): err is FetchBaseQueryError => {
Ok

2023-06-21 20:40 UTC, kas1qqqq commented on src/components/modules/SignUpSection/SignUpForm.tsx
> +    const isFetchBaseQueryError = (err: unknown): err is FetchBaseQueryError => {
Ok

2023-06-22 12:12 UTC, kas1qqqq commented on src/components/elements/Auth/Auth.tsx
> +    error?: ErrorProps | any;
In the last commit, I reworked this logic

2023-06-24 18:57 UTC, karinabarinova approved these changes

2023-06-30 06:44 UTC, DevMoroh approved these changes

2023-06-30 06:54 UTC, merged